// Glossary for transport streams: the structures and the concepts a newcomer
// needs to read a TS (clocks, tables, packetisation, broadcast conventions).

const H222 = 'https://www.itu.int/rec/T-REC-H.222.0';
const EN300468 = 'https://www.etsi.org/deliver/etsi_en/300400_300499/300468/';
const TR101290 = 'https://www.etsi.org/deliver/etsi_tr/101200_101299/101290/';

const ENTRIES = [
  {
    term: 'TS packet',
    name: 'Transport stream packet',
    cat: 'media',
    desc: 'The fixed 188-byte unit of an MPEG-2 transport stream: a 4-byte header, an optional adaptation field and up to 184 bytes of payload.',
    more: 'Fixed-size packets make the format robust for broadcast and networks: a receiver can join at any point, find packet boundaries from the sync byte, and lose a packet without losing the rest. Seven packets (1,316 bytes) fit in one UDP datagram, which is how IPTV and SRT carry TS.',
    url: H222,
  },
  {
    term: 'sync byte',
    name: 'sync_byte (0x47)',
    cat: 'header',
    desc: 'The first byte of every packet, always 0x47 (ASCII "G"). Demuxers find packet boundaries by checking that it repeats every 188 bytes.',
    more: 'A receiver declares sync when several consecutive packets start with 0x47 and drops sync after a few misses (TR 101 290 TS_sync_loss). The same trick detects 192-byte M2TS and 204-byte packets: only the period changes.',
  },
  {
    term: 'PID',
    name: 'Packet identifier',
    cat: 'header',
    desc: 'The 13-bit number in every packet header that says which stream the packet belongs to (0–8191).',
    more: 'A transport stream multiplexes many streams by interleaving their packets; the PID is the only thing that tells them apart. PID 0x0000 carries the PAT and 0x1FFF null packets; the PAT and PMTs assign every other PID a meaning. DVB reserves 0x0010–0x001F for its service information tables.',
  },
  {
    term: 'PUSI',
    name: 'payload_unit_start_indicator',
    cat: 'header',
    desc: 'Header flag set on the packet where a new PES packet begins, or where at least one new PSI section begins (then the first payload byte is a pointer_field).',
    more: 'It is how a demuxer finds the start of each frame without parsing the whole payload: a PES packet runs from one PUSI packet to the next packet with PUSI on the same PID.',
  },
  {
    term: 'continuity counter',
    name: 'continuity_counter',
    cat: 'header',
    desc: 'A 4-bit counter per PID that increments (modulo 16) on every packet carrying payload, so receivers can detect lost packets.',
    more: 'A jump means packets were lost (TR 101 290 Continuity_count_error); the same value twice is a permitted duplicate. Packets without payload do not advance it, and discontinuity_indicator allows a reset, for example after a splice.',
    url: TR101290,
  },
  {
    term: 'adaptation field',
    name: 'Adaptation field',
    cat: 'header',
    desc: 'Optional part of a packet after the header, used for the PCR, random-access and discontinuity flags, splice countdowns, private data and stuffing.',
    more: 'adaptation_field_control in the header says whether it is present. Because packets are always 188 bytes, the adaptation field also absorbs padding: the last packet of a PES packet carries 0xFF stuffing bytes when the data runs out.',
    url: H222,
  },
  {
    term: 'PCR',
    name: 'Program Clock Reference',
    cat: 'header',
    desc: 'A 42-bit sample of the encoder’s 27 MHz system clock (a 90 kHz base × 300 plus a 0–299 extension), carried in adaptation fields of the program’s PCR PID.',
    more: 'The decoder uses successive PCRs to lock its own clock to the encoder’s, so that audio and video are presented at exactly the rate they were captured and its buffers neither overflow nor underflow. ISO/IEC 13818-1 requires a PCR at least every 100 ms; DVB asks for 40 ms. Its accuracy must be within ±500 ns.',
    url: H222,
  },
  {
    term: 'OPCR',
    name: 'Original Program Clock Reference',
    cat: 'header',
    desc: 'A copy of the PCR from the original transport stream, kept when a program is extracted into another multiplex so the original timing can be restored.',
  },
  {
    term: 'random access indicator',
    name: 'random_access_indicator',
    cat: 'header',
    desc: 'Adaptation-field flag announcing that the next PES packet of the PID begins at a random access point: a video key frame (with the headers needed to decode it) or an audio frame start.',
    more: 'HLS segmenters, DVR indexers and players seeking in a TS often rely on this flag instead of parsing the video. A key frame without it may be invisible to them.',
  },
  {
    term: 'discontinuity indicator',
    name: 'discontinuity_indicator',
    cat: 'header',
    desc: 'Adaptation-field flag saying that the continuity counter and/or the PCR time base legitimately restart at this packet (for example at a splice between two sources).',
  },
  {
    term: 'PES',
    name: 'Packetized Elementary Stream',
    cat: 'media',
    desc: 'The intermediate packet layer between codec frames and transport packets: each PES packet has a header with the stream_id, a length and the PTS/DTS, followed by the frame data.',
    more: 'Usually one video frame per PES packet; audio PES packets often hold several frames. A PES packet is cut into as many 184-byte transport packet payloads as needed. The same PES packets are used in MPEG program streams (DVD .VOB, .mpg).',
    url: H222,
  },
  {
    term: 'stream_id',
    name: 'PES stream_id',
    cat: 'header',
    desc: 'The byte after the PES start code 00 00 01 that names the kind of stream: 0xE0–0xEF video, 0xC0–0xDF MPEG audio, 0xBD private_stream_1 (AC-3, DTS, DVB subtitles...), 0xBE padding.',
    more: 'In a transport stream the PMT stream_type is authoritative; the stream_id matters more in program streams, where there is no PMT.',
  },
  {
    term: 'PTS',
    name: 'Presentation Time Stamp',
    cat: 'header',
    desc: 'The time, on the program’s 90 kHz clock, at which the first frame starting in a PES packet must be displayed or played. 33 bits, so it wraps after about 26.5 hours.',
    more: 'PTS values are meaningful only relative to the PCR of the same program; they usually start at an arbitrary value (FFmpeg starts at 1.4 s). Players synchronise audio and video by comparing their PTS. ISO/IEC 13818-1 requires one at least every 700 ms.',
  },
  {
    term: 'DTS',
    name: 'Decode Time Stamp',
    cat: 'header',
    desc: 'When a frame must be decoded, on the same 90 kHz clock. Sent only when it differs from the PTS, which happens for video with B-frames (frames are transmitted in decoding order, not display order).',
  },
  {
    term: 'timestamp wrap',
    name: '33-bit wrap-around',
    cat: 'header',
    desc: 'PTS, DTS and the PCR base are 33-bit counters of a 90 kHz clock: after 2^33 ticks (about 26 h 30 min) they wrap to zero.',
    more: 'Long-running live streams wrap regularly, so demuxers must unwrap timestamps instead of assuming they only grow. Tools that do not are a classic source of A/V desync in recordings.',
  },
  {
    term: 'elementary stream',
    name: 'Elementary stream (ES)',
    cat: 'media',
    desc: 'The output of one encoder: a single video, audio, subtitle or data stream. Each is packetised into PES packets and carried on its own PID.',
  },
  {
    term: 'program',
    name: 'Program (DVB: service)',
    cat: 'table',
    desc: 'A group of elementary streams presented together, with one clock: typically one TV channel. A multiplex can carry several programs; a file usually carries one.',
    more: 'The PAT lists the programs; each program’s PMT lists its streams and its PCR PID. DVB calls programs services and names them in the SDT.',
  },
  {
    term: 'PSI',
    name: 'Program Specific Information',
    cat: 'table',
    desc: 'The tables ISO/IEC 13818-1 defines to describe a transport stream: PAT, PMT, CAT (and the NIT, whose content is left to the broadcast system).',
    more: 'DVB adds service information (SI) tables such as SDT, EIT and TDT (ETSI EN 300 468); ATSC adds PSIP. Together they are often called PSI/SI.',
    url: H222,
  },
  {
    term: 'section',
    name: 'Section',
    cat: 'table',
    desc: 'The unit in which tables are transmitted: table_id, section_length, (usually) version and section numbers, the table data and a CRC_32. Up to 1,024 bytes for PSI, 4,096 for private sections.',
    more: 'Sections are cut into transport packets like PES packets, but a packet may contain the end of one section and the start of the next: the pointer_field says where the new one starts.',
  },
  {
    term: 'pointer_field',
    name: 'pointer_field',
    cat: 'table',
    desc: 'The first payload byte of a packet with PUSI on a table PID: the number of bytes (belonging to the previous section) before the first new section starts.',
  },
  {
    term: 'CRC_32',
    name: 'Section CRC',
    cat: 'table',
    desc: 'A 32-bit checksum (CRC-32/MPEG-2) at the end of long sections. A receiver drops a section whose CRC fails.',
  },
  {
    term: 'PAT',
    name: 'Program Association Table',
    cat: 'table',
    desc: 'Table on PID 0x0000 that lists every program and the PID of its PMT (program 0 points to the NIT). The first thing a receiver reads.',
    more: 'Tune-in time depends on how often it repeats: typically every 100 ms; TR 101 290 flags gaps over 0.5 s.',
    url: H222,
  },
  {
    term: 'PMT',
    name: 'Program Map Table',
    cat: 'table',
    desc: 'Table describing one program: its PCR PID and, for each elementary stream, the stream_type (codec), the PID and descriptors (language, codec details...).',
    url: H222,
  },
  {
    term: 'CAT',
    name: 'Conditional Access Table',
    cat: 'protect',
    desc: 'Table on PID 0x0001 listing the conditional-access systems in use and the PIDs of their EMMs. Present only in scrambled streams.',
  },
  {
    term: 'ECM / EMM',
    name: 'Entitlement Control / Management Messages',
    cat: 'protect',
    desc: 'Conditional-access messages: ECMs carry the (encrypted) control words that descramble a program, EMMs deliver subscription rights to smart cards. Their PIDs come from CA descriptors in the PMT and the CAT.',
  },
  {
    term: 'scrambling',
    name: 'transport_scrambling_control',
    cat: 'protect',
    desc: 'Two header bits saying whether the payload of a packet is encrypted (DVB-CSA and similar); in DVB 10 and 11 select the even or odd control word.',
    more: 'Headers and adaptation fields stay in the clear so the stream can still be demultiplexed and timed without the keys.',
  },
  {
    term: 'stream_type',
    name: 'stream_type',
    cat: 'codec',
    desc: 'The byte in the PMT that says which coding format an elementary stream uses: 0x02 MPEG-2 video, 0x0F AAC (ADTS), 0x1B H.264, 0x24 HEVC, 0x03/0x04 MPEG audio, 0x06 private data...',
    more: 'Values 0x80–0xFF are "user private" and depend on the system: 0x81 is AC-3 in ATSC and Blu-ray, 0x86 is SCTE-35 in cable systems but DTS-HD MA on Blu-ray. DVB instead uses 0x06 plus a descriptor (AC-3, E-AC-3, subtitles, teletext).',
    url: H222,
  },
  {
    term: 'descriptor',
    name: 'Descriptor',
    cat: 'table',
    desc: 'A tag-length-value record attached to a program, stream, service or event in PSI/SI tables: language, registration, codec parameters, maximum bitrate, service name...',
    more: 'Because every descriptor carries its length, receivers skip tags they do not understand, which lets standards add new ones without breaking old decoders.',
  },
  {
    term: 'registration descriptor',
    name: 'registration_descriptor',
    cat: 'codec',
    desc: 'Descriptor (tag 0x05) with a four-character format_identifier registered with SMPTE-RA, naming private formats: \'AC-3\', \'EAC3\', \'HEVC\', \'Opus\', \'KLVA\', \'CUEI\' (SCTE-35), \'HDMV\' (Blu-ray)...',
  },
  {
    term: 'NIT',
    name: 'Network Information Table',
    cat: 'table',
    desc: 'DVB table (on the PID given by program 0 of the PAT, 0x0010) describing the network: its name and the transport streams it carries with their tuning parameters.',
    url: EN300468,
  },
  {
    term: 'SDT',
    name: 'Service Description Table',
    cat: 'table',
    desc: 'DVB table on PID 0x0011 naming each service (channel) and its provider, with its type (TV, radio...). FFmpeg writes one with "Service01" / "FFmpeg" by default.',
    url: EN300468,
  },
  {
    term: 'EIT',
    name: 'Event Information Table',
    cat: 'table',
    desc: 'DVB programme-guide table on PID 0x0012: the present/following events and the schedule of each service, with titles, descriptions, start times and durations.',
    url: EN300468,
  },
  {
    term: 'TDT / TOT',
    name: 'Time and Date / Time Offset Table',
    cat: 'table',
    desc: 'DVB tables on PID 0x0014 carrying the current UTC time (and local time offsets in the TOT) so receivers can set their clocks.',
    url: EN300468,
  },
  {
    term: 'null packet',
    name: 'Null packet',
    cat: 'free',
    desc: 'A stuffing packet on PID 0x1FFF whose payload is meaningless. Multiplexers insert them to keep a constant bitrate.',
    more: 'Broadcast and IPTV links need exactly N bits per second, so spare capacity is filled with null packets. For files and HTTP delivery (HLS), they are pure overhead and remuxers drop them.',
  },
  {
    term: 'CBR / VBR multiplex',
    name: 'Constant or variable bitrate transport stream',
    cat: 'media',
    desc: 'A CBR TS sends packets at a fixed rate (the mux rate), padded with null packets; a VBR TS writes packets only as needed. FFmpeg writes VBR unless -muxrate is given.',
  },
  {
    term: 'T-STD',
    name: 'Transport stream System Target Decoder',
    cat: 'media',
    desc: 'The idealised decoder model of ISO/IEC 13818-1: packets enter buffers at the time given by the PCR and each frame is removed at its DTS. A conforming multiplex never makes these buffers overflow or underflow.',
    more: 'The gap between a frame’s arrival (PCR time) and its DTS is the buffering delay a multiplexer chooses; if a frame arrives after its DTS, a real decoder has to drop or repeat pictures.',
    url: H222,
  },
  {
    term: 'TR 101 290',
    name: 'ETSI TR 101 290',
    cat: 'meta',
    desc: 'The DVB measurement guideline that defines the standard checks for transport streams, in three priorities: sync, PAT/PMT and continuity (1); CRC, PCR and PTS timing (2); SI repetition and unreferenced PIDs (3).',
    url: TR101290,
  },
  {
    term: 'SCTE-35',
    name: 'SCTE-35 splice information',
    cat: 'meta',
    desc: 'Cue messages (splice_info_section, table_id 0xFC) that mark ad breaks and program boundaries in a TS, usually on a PID with stream_type 0x86.',
    more: 'Ad-insertion systems splice ads at these points; HLS and DASH packagers turn them into playlist tags or events.',
    url: 'https://en.wikipedia.org/wiki/SCTE-35',
  },
  {
    term: 'M2TS',
    name: 'BDAV MPEG-2 transport stream (.m2ts, .mts)',
    cat: 'media',
    desc: 'The transport stream variant of Blu-ray and AVCHD cameras: 192-byte packets made of a 4-byte TP_extra_header and a normal 188-byte packet.',
    more: 'The extra header holds a 30-bit arrival_time_stamp (27 MHz) and 2 copy-permission bits. Blu-ray also gives the private stream types 0x80–0xA2 their own meaning (LPCM, TrueHD, DTS-HD, PGS subtitles) and signals it with the \'HDMV\' registration descriptor.',
    url: 'https://en.wikipedia.org/wiki/.m2ts',
  },
  {
    term: 'arrival_time_stamp',
    name: 'Arrival time stamp (ATS)',
    cat: 'header',
    desc: 'The 30-bit, 27 MHz time at which an M2TS packet arrived at the recorder. A player releases packets to the decoder at these times, reproducing the timing of the original broadcast.',
  },
  {
    term: '204-byte packets',
    name: 'Packets with Reed-Solomon parity',
    cat: 'media',
    desc: 'Captures from DVB demodulators or DVB-ASI sometimes keep 16 bytes of Reed-Solomon RS(204,188) parity after each 188-byte packet, giving 204-byte units.',
  },
  {
    term: 'ADTS',
    name: 'Audio Data Transport Stream',
    cat: 'codec',
    desc: 'The framing of AAC in transport streams (stream_type 0x0F): every AAC frame starts with a 7- or 9-byte header (sync word 0xFFF, profile, sample rate, channels, frame length).',
    more: 'Because each frame is self-describing, a decoder can start anywhere. MP4 stores AAC without these headers and puts the configuration in the esds box instead.',
  },
  {
    term: 'LATM / LOAS',
    name: 'Low-overhead MPEG-4 Audio Transport Multiplex',
    cat: 'codec',
    desc: 'An alternative AAC framing (stream_type 0x11), used by DVB-T2 and ISDB broadcasts: LOAS sync frames (0x2B7) carrying the audio configuration in-band.',
  },
  {
    term: 'Annex B',
    name: 'Annex B byte stream',
    cat: 'codec',
    desc: 'The framing of H.264/HEVC in transport streams: NAL units separated by start codes 00 00 01 (or 00 00 00 01), with the parameter sets (SPS/PPS) repeated in the stream.',
    more: 'MP4 and Matroska use length prefixes instead and keep the parameter sets in the sample entry (avcC/hvcC); converting between the two is what h264_mp4toannexb does.',
  },
  {
    term: 'access unit delimiter',
    name: 'Access unit delimiter (AUD)',
    cat: 'codec',
    desc: 'A tiny NAL unit (type 9 in H.264, 35 in HEVC) marking the start of each frame. Required for H.264 in transport streams by DVB and Blu-ray, and written by FFmpeg.',
  },
  {
    term: 'HLS',
    name: 'HTTP Live Streaming',
    cat: 'media',
    desc: 'Apple’s adaptive streaming protocol, which historically delivers media as short MPEG-TS segments (a few seconds each) listed in .m3u8 playlists. RFC 8216 asks for a PAT and PMT at the start of every segment, and segments should begin with a key frame so each can be decoded on its own.',
  },
  {
    term: 'DVB / ATSC',
    name: 'Broadcast systems',
    cat: 'meta',
    desc: 'DVB (Europe and much of the world) and ATSC (North America) both use MPEG-2 transport streams but add different service information tables (SDT/EIT vs PSIP) and different conventions for private stream types.',
  },
];

export function glossary() {
  return ENTRIES;
}
